// Authentication
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHANGE_USERNAME_INPUT = 'CHANGE_USERNAME_INPUT';
export const CHANGE_PASSWORD_INPUT = 'CHANGE_PASSWORD_INPUT';
// Sign up
export const SIGN_UP = 'SIGN_UP';
export const CHANGE_FIRST_NAME_SIGN_UP_INPUT = 'CHANGE_FIRST_NAME_SIGN_UP_INPUT';
export const CHANGE_LAST_NAME_SIGN_UP_INPUT = 'CHANGE_LAST_NAME_SIGN_UP_INPUT';
export const CHANGE_EMAIL_SIGN_UP_INPUT = 'CHANGE_EMAIL_SIGN_UP_INPUT';
export const CHANGE_PASSWORD_SIGN_UP_INPUT = 'CHANGE_PASSWORD_SIGN_UP_INPUT';
export const CHANGE_PASSWORD_CONFIRMATION_SIGN_UP_INPUT = 'CHANGE_PASSWORD_CONFIRMATION_SIGN_UP_INPUT';
